/**
 * Havfen Community-API
 * Hafven Community API [Development]. This might link to the homepage [http://hafven-community.ngrok.io](http://hafven-community.ngrok.io). Notice that all html tags are valid in this description. Feel free to be descriptive.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@hafven-community.ngrok.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HavfenCommunityApi);
  }
}(this, function(expect, HavfenCommunityApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HavfenCommunityApi.Meetup();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Meetup', function() {
    it('should create an instance of Meetup', function() {
      // uncomment below and update the code to test Meetup
      //var instane = new HavfenCommunityApi.Meetup();
      //expect(instance).to.be.a(HavfenCommunityApi.Meetup);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new HavfenCommunityApi.Meetup();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "groupId")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new HavfenCommunityApi.Meetup();
      //expect(instance).to.be();
    });

    it('should have the property suggestedDate (base name: "suggestedDate")', function() {
      // uncomment below and update the code to test the property suggestedDate
      //var instane = new HavfenCommunityApi.Meetup();
      //expect(instance).to.be();
    });

    it('should have the property eventDate (base name: "eventDate")', function() {
      // uncomment below and update the code to test the property eventDate
      //var instane = new HavfenCommunityApi.Meetup();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new HavfenCommunityApi.Meetup();
      //expect(instance).to.be();
    });

    it('should have the property complete (base name: "complete")', function() {
      // uncomment below and update the code to test the property complete
      //var instane = new HavfenCommunityApi.Meetup();
      //expect(instance).to.be();
    });

  });

}));
