/**
 * Havfen Community-API
 * Hafven Community API [Development]. This might link to the homepage [http://hafven-community.ngrok.io](http://hafven-community.ngrok.io). Notice that all html tags are valid in this description. Feel free to be descriptive.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@hafven-community.ngrok.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HavfenCommunityApi) {
      root.HavfenCommunityApi = {};
    }
    root.HavfenCommunityApi.Meetup = factory(root.HavfenCommunityApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Meetup model module.
   * @module model/Meetup
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Meetup</code>.
   * @alias module:model/Meetup
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Meetup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Meetup} obj Optional instance to populate.
   * @return {module:model/Meetup} The populated <code>Meetup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'Number');
      }
      if (data.hasOwnProperty('suggestedDate')) {
        obj['suggestedDate'] = ApiClient.convertToType(data['suggestedDate'], 'Date');
      }
      if (data.hasOwnProperty('eventDate')) {
        obj['eventDate'] = ApiClient.convertToType(data['eventDate'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('complete')) {
        obj['complete'] = ApiClient.convertToType(data['complete'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * @member {Date} suggestedDate
   */
  exports.prototype['suggestedDate'] = undefined;
  /**
   * @member {Date} eventDate
   */
  exports.prototype['eventDate'] = undefined;
  /**
   * Meetup Status
   * @member {module:model/Meetup.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Boolean} complete
   * @default false
   */
  exports.prototype['complete'] = false;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "placed"
     * @const
     */
    "placed": "placed",
    /**
     * value: "approved"
     * @const
     */
    "approved": "approved",
    /**
     * value: "cancelled"
     * @const
     */
    "cancelled": "cancelled"  };


  return exports;
}));


