/**
 * Havfen Community-API
 * Hafven Community API [Development]. This might link to the homepage [http://hafven-community.ngrok.io](http://hafven-community.ngrok.io). Notice that all html tags are valid in this description. Feel free to be descriptive.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@hafven-community.ngrok.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiResponse', 'model/Category', 'model/Group', 'model/Meetup', 'model/Tag', 'model/User', 'api/CommunityApi', 'api/GroupsApi', 'api/MeetupsApi', 'api/UserApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ApiResponse'), require('./model/Category'), require('./model/Group'), require('./model/Meetup'), require('./model/Tag'), require('./model/User'), require('./api/CommunityApi'), require('./api/GroupsApi'), require('./api/MeetupsApi'), require('./api/UserApi'));
  }
}(function(ApiClient, ApiResponse, Category, Group, Meetup, Tag, User, CommunityApi, GroupsApi, MeetupsApi, UserApi) {
  'use strict';

  /**
   * Hafven_Community_API__Development__This_might_link_to_the_homepage__httphafven_community_ngrok_io_httphafven_community_ngrok_io__Notice_that_all_html_tags_are_valid_in_this_description__Feel_free_to_be_descriptive_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var HavfenCommunityApi = require('index'); // See note below*.
   * var xxxSvc = new HavfenCommunityApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new HavfenCommunityApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new HavfenCommunityApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new HavfenCommunityApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ApiResponse model constructor.
     * @property {module:model/ApiResponse}
     */
    ApiResponse: ApiResponse,
    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category: Category,
    /**
     * The Group model constructor.
     * @property {module:model/Group}
     */
    Group: Group,
    /**
     * The Meetup model constructor.
     * @property {module:model/Meetup}
     */
    Meetup: Meetup,
    /**
     * The Tag model constructor.
     * @property {module:model/Tag}
     */
    Tag: Tag,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The CommunityApi service constructor.
     * @property {module:api/CommunityApi}
     */
    CommunityApi: CommunityApi,
    /**
     * The GroupsApi service constructor.
     * @property {module:api/GroupsApi}
     */
    GroupsApi: GroupsApi,
    /**
     * The MeetupsApi service constructor.
     * @property {module:api/MeetupsApi}
     */
    MeetupsApi: MeetupsApi,
    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
    UserApi: UserApi
  };

  return exports;
}));
